tests: In partmap_test, use ${parted} variable when checking for binary
Signed-off-by: Glenn Washburn <development@efficientek.com>
Reviewed-by: Daniel Kiper <daniel.kiper@oracle.com>

diff --git a/tests/partmap_test.in b/tests/partmap_test.in
--- a/tests/partmap_test.in
+++ b/tests/partmap_test.in
@@ -96,8 +96,8 @@ case "${grub_modinfo_target_cpu}-${grub_modinfo_platform}" in
 	;;
 esac
 
-if ! which parted >/dev/null 2>&1; then
-   echo "parted not installed; cannot test partmap"
+if ! which ${parted} >/dev/null 2>&1; then
+   echo "${parted} not installed; cannot test partmap"
    exit 99
 fi
 
